[package]
name = "ddd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
typed-index-collections = "3.0"
log = "0.4"
pretty_env_logger = "0.4"
ipamir-rs = { version = "0.1.0", path = "../ipamir-rs" }
